device: /dev/ttyACM1
frame_id: gps_base
baudrate: 19200       # C94-M8P specific
rate: 4               #  in Hz
rtcm_ids: [5, 87, 77, 230]  # RTCM Messages to configure for Base station
rtcm_rate: 1          # in Hz
enable_sbas: false    # Not supported by C94-M8P
enable_glonass: true  # Supported by C94-M8P
enable_beidou: false  # Supported by C94-M8P
enable_qzss: true  # Supported by C94-M8P
enable_ppp: false
all: true
# Velocity restricted to 0 m/s. Zero dynamics assumed.
dynamic_model: stationary
fix_mode: auto
dr_limit: 0
ublox_version: 8