device: /dev/ttyACM2
frame_id: gps
baudrate: 19200       # C94-M8P specific
rate: 10  #  in Hz
enable_sbas: false    # Not supported by C94-M8P
enable_glonass: true  # Supported by C94-M8P
enable_beidou: false  # Supported by C94-M8P
enable_qzss: true  # Supported by C94-M8P
enable_ppp: false
# Airborne < 2G, 2D fix not supported (3D only), 
# Max Alt: 50km, Max Horizontal Velocity: 250 m/s, Max Vertical Velocity: 100 m/s
dynamic_model: airborne2
fix_mode: both
dr_limit: 0
ublox_version: 8

# Subscriptions
all: true
aid: true
aid_alm: true
aid_eph: true
aid_hui: true
nav_sol: true
nav_pvt: true
nav_status: true
nav_svinfo: true
nav_clk: true
nav_posllh: true
nav_posecef: false
nav_velned: false
rxm: true
rxm_raw: true
rxm_sfrb: true